version: "3"
services:
    app:
        container_name: Muesli_Machine_App
        build: ./app
        ports:
            - ${APP_PORT}:80
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        environment:
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_USER: root
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}

    db:
        container_name: Muesli_Machine_MySQL
        image: hypriot/rpi-mysql
        restart: always
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_HOST: localhost
        volumes:
            - ./db:/var/lib/mysql
    pma:
        container_name: phpmyadmin
        image: mt08/rpi-phpmyadmin
        restart: always
        links:
          - db:db
        ports:
            - 8181:80
        environment:
#              PMA_HOST: localhost
              PMA_USER: root
              PMA_PASSWORD: ${DB_PASS}
