CREATE TABLE `{2}`(
    tube_uid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tube_gpio_1 INT(3) UNSIGNED NOT NULL,
    tube_gpio_2 INT(3) UNSIGNED NOT NULL,
    tube_gpio_3 INT(3) UNSIGNED NOT NULL,
    tube_gpio_4 INT(3) UNSIGNED NOT NULL
) ENGINE=INNODB